### ISSUE TITLE
Assistance in Running simple-spifit

### ISSUE THREAD

**Issue by PNMwaniki** [landmanbester/spimple#16]
jax error when running simple-spifit worker.
i.e. AttributeError: module 'jax.config' has no attribute 'update'

**Comment by landmanbester** [comment]
Thanks for reporting. I believe the error is coming from `codex-africanus`. Please post the full traceback and also the output of `pip freeze`

**Comment by PNMwaniki** [comment]
Traceback (most recent call last):
  File "/users/pnmwaniki/.venv/spimple/bin/spimple-spifit", line 33, in <module>
    sys.exit(load_entry_point('spimple', 'console_scripts', 'spimple-spifit')())
  File "/users/pnmwaniki/.venv/spimple/bin/spimple-spifit", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/users/pnmwaniki/software/spectral/spimple/spimple/apps/spi_fitter.py", line 12, in <module>
    from spimple.utils import (load_fits, save_fits, convolve2gaussres, data_from_header,
  File "/users/pnmwaniki/software/spectral/spimple/spimple/utils.py", line 7, in <module>
    from africanus.rime.dask import beam_cube_dde
  File "/users/pnmwaniki/.venv/spimple/lib/python3.10/site-packages/africanus/__init__.py", line 10, in <module>
    import africanus.util.jax_init  # noqa
  File "/users/pnmwaniki/.venv/spimple/lib/python3.10/site-packages/africanus/util/jax_init.py", line 14, in <module>
    jax.config.update("jax_enable_x64", True)
AttributeError: module 'jax.config' has no attribute 'update'

**Comment by landmanbester** [comment]
Thanks @PNMwaniki I have reported the problem https://github.com/ratt-ru/codex-africanus/issues/295. We'll get a fix for you asap

**Comment by landmanbester** [comment]
@PNMwaniki this problem should be fixed if you install codex-africanus from source i.e.

```
$ git clone https://github.com/ratt-ru/codex-africanus.git
$ pip install -e codex-africanus[complete]  # or using quotes i.e. 'codex-africanus[complete]' on zsh
```

Make sure to update your pip in the virtualenv before doing this.
I'll keep the issue open until there is a release of africanus with the fix.
Please let me know if you run into any further issues

**Comment by landmanbester** [comment]
Fixed be fixed in the latest release. Please reopen if not
