### ISSUE TITLE
Issues with specifying reference frequency

### ISSUE THREAD

**Issue by MikaNaidoo** [landmanbester/spimple#18]
I am getting the following error when trying to run the following command -- the issue arises when trying to specify the reference frequency:
`spimple-spifit -model vlacleanmodelcube.fits -o imap -products i -rf 1519500000` 
full error:
```Traceback (most recent call last):
  File "/home/mika/.stimelaenv/bin/spimple-spifit", line 33, in <module>
    sys.exit(load_entry_point('spimple==0.0.4', 'console_scripts', 'spimple-spifit')())
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/spimple/apps/spi_fitter.py", line 104, in spi_fitter
    opts = OmegaConf.create(vars(opts))
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 178, in create
    return OmegaConf._create_impl(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 900, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 861, in _create_impl
    return DictConfig(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 109, in __init__
    self._set_value(content, flags=flags)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 647, in _set_value
    raise e
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 644, in _set_value
    self._set_value_impl(value, flags)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 690, in _set_value_impl
    self.__setitem__(k, v)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 314, in __setitem__
    self._format_and_raise(key=key, value=value, cause=e)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 620, in _set_item_impl
    self._wrap_value_and_set(key, value, target_type_hint)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 636, in _wrap_value_and_set
    self._format_and_raise(key=key, value=val, cause=e)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 628, in _wrap_value_and_set
    wrapped = _maybe_wrap(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1105, in _maybe_wrap
    return _node_wrap(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 1045, in _node_wrap
    node = AnyNode(value=value, key=key, parent=parent)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/nodes.py", line 135, in __init__
    super().__init__(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/nodes.py", line 29, in __init__
    self._set_value(value)  # lgtm [py/init-calls-subclass]
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/nodes.py", line 76, in validate_and_convert
    return self._validate_and_convert_impl(value)
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/omegaconf/nodes.py", line 154, in _validate_and_convert_impl
    raise UnsupportedValueType(
omegaconf.errors.UnsupportedValueType: Value 'float64' is not a supported primitive type
    full_key: ref_freq
    object_type=dict```

**Comment by MikaNaidoo** [comment]
I am also experiencing issues when I enable the `--dont-convolve` option. I run the following command:
`spimple-spifit -model vlacleanmodelcube.fits -o spifits -products a -dc`, and get the following error:
```Traceback (most recent call last):
  File "/home/mika/.stimelaenv/bin/spimple-spifit", line 33, in <module>
    sys.exit(load_entry_point('spimple==0.0.4', 'console_scripts', 'spimple-spifit')())
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/spimple/apps/spi_fitter.py", line 428, in spi_fitter
    fitcube = da.from_array(fitcube.astype(np.float64),
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3488, in from_array
    chunks = normalize_chunks(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3104, in normalize_chunks
    chunks = sum(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3106, in <genexpr>
    blockdims_from_blockshape((s,), (c,))
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 1270, in blockdims_from_blockshape
    return tuple(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 1271, in <genexpr>
    ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
ZeroDivisionError: integer division or modulo by zero```

**Comment by landmanbester** [comment]
I just pushed a fix for this problem to the issue18 branch (I moved the second problem to a separate issue https://github.com/landmanbester/spimple/issues/19). You will have to install in editable mode to test it. Seems like it was just a leftover `np.float64` in the argparse which then trips up omegaconf
