### ISSUE TITLE
Problem when enabling the `--dont-convolve` option

### ISSUE THREAD

**Issue by landmanbester** [landmanbester/spimple#19]
I am also experiencing issues when I enable the `--dont-convolve` option. I run the following command:
`spimple-spifit -model vlacleanmodelcube.fits -o spifits -products a -dc`, and get the following error:
```Traceback (most recent call last):
  File "/home/mika/.stimelaenv/bin/spimple-spifit", line 33, in <module>
    sys.exit(load_entry_point('spimple==0.0.4', 'console_scripts', 'spimple-spifit')())
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/spimple/apps/spi_fitter.py", line 428, in spi_fitter
    fitcube = da.from_array(fitcube.astype(np.float64),
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3488, in from_array
    chunks = normalize_chunks(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3104, in normalize_chunks
    chunks = sum(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 3106, in <genexpr>
    blockdims_from_blockshape((s,), (c,))
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 1270, in blockdims_from_blockshape
    return tuple(
  File "/home/mika/.stimelaenv/lib/python3.10/site-packages/dask/array/core.py", line 1271, in <genexpr>
    ((bd,) * (d // bd) + ((d % bd,) if d % bd else ()) if d else (0,))
ZeroDivisionError: integer division or modulo by zero```

_Originally posted by @MikaNaidoo in https://github.com/landmanbester/spimple/issues/18#issuecomment-2433230851_

**Comment by landmanbester** [comment]
From https://github.com/landmanbester/spimple/issues/18

**Comment by MikaNaidoo** [comment]
Just figured out that the problem is this

https://github.com/landmanbester/spimple/blob/ba3692c640be261ec9598b6322e12f4821e4ab7b/spimple/apps/spi_fitter.py#L428-L431

If `ncomps/nthreads < 1` then it gives the number of chunks as 0 to dask which then gives the above error. When I try with threads less than the number of computations it worked.

**Comment by landmanbester** [comment]
Ah, ok. I will add a fix for that, thanks for reporting. Note that you may have to play with the `--maxDR` parameter to set your thresholds if you are not passing in a residual image. Only components above image-peak/maxDR will be fit. Not sure how suitable the default value of 100 is for your field

**Comment by landmanbester** [comment]
Should be fixed when https://github.com/landmanbester/spimple/pull/21 goes in
